# Generated by Django 4.1.11 on 2023-10-01 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scraper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobListings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("link", models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name="Job",
        ),
    ]
