# Generated by Django 4.1.11 on 2023-10-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scraper", "0002_joblistings_delete_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblistings",
            name="company",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="joblistings",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="joblistings",
            name="location",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="joblistings",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
