# Generated by Django 4.1.11 on 2023-10-17 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scraper", "0004_joblistings_closed_joblistings_sponsorship"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="joblistings",
            name="categories",
            field=models.ManyToManyField(to="Scraper.category"),
        ),
    ]
