# Generated by Django 4.1.11 on 2023-10-17 01:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scraper", "0005_category_joblistings_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joblistings",
            name="categories",
        ),
        migrations.AddField(
            model_name="joblistings",
            name="categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
