# Generated by Django 4.1.11 on 2023-10-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scraper", "0007_rename_link_joblistings_apply_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblistings",
            name="company_link",
            field=models.URLField(default=""),
        ),
    ]
