# Generated by Django 4.1.11 on 2023-10-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scraper", "0010_alter_joblistings_apply_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblistings",
            name="company",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="joblistings",
            name="location",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="joblistings",
            name="title",
            field=models.CharField(default="", max_length=500),
        ),
    ]
