# Generated by Django 4.1.11 on 2023-10-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Scraper",
            "0011_alter_joblistings_company_alter_joblistings_location_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblistings",
            name="location",
            field=models.CharField(default="", max_length=10000),
        ),
    ]
