# Generated by Django 4.1.11 on 2023-10-17 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Scraper", "0012_alter_joblistings_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joblistings",
            name="description",
        ),
    ]
