# Generated by Django 4.1.11 on 2023-10-20 02:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scraper", "0015_remove_joblistings_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblistings",
            name="locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
