# Generated by Django 4.1.11 on 2023-10-20 02:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scraper", "0016_joblistings_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblistings",
            name="locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=1000),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
