# Generated by Django 4.1.11 on 2023-10-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scraper", "0017_alter_joblistings_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblistings",
            name="company_logo",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
