# Generated by Django 4.1.11 on 2023-10-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Scraper", "0019_alter_joblistings_company_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
