version: "3"

services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/back
    command: >
      sh -c "python3 manage.py wait_for_db && python3 manage.py migrate && gunicorn back.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - back

  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  celery:
    restart: always
    build:
      context: .
    command: celery -A back worker --loglevel=info
    volumes:
      - .:/back
    env_file:
      - ./.env
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.2
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
