version: "3"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=False
      - SECRET_KEY=django-insecure-0p1xl4)+u+l)%%scg8aq%=r90+k+^6#w2*i4-o^sf6v9kvqwpc
      # Add your Django secret key and other environment variables

  celery:
    build: .
    command: celery -A back worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=internio
      - POSTGRES_PASSWORD=internioDvc123

  redis:
    image: redis:latest
